[package]
name = "wasmql"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "wasmql-macros",
]

[dependencies]
postcard = { version = "1", features = ["alloc"], default-features = false }
serde = { version = "1", features = ["derive"], default-features = false }
wasmql-macros = { path = "wasmql-macros" }

[build-dependencies]
minify-js = { version = "0.5.6", default-features = false }
