[package]
name = "poem"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["protocol"]

[profile.release]
lto = "thin"
opt-level = "z"
panic = "abort"
strip = "symbols"

[dependencies]
poem = "1"
wasmql = { path = "../.." }

[build-dependencies]
wasmql-build = { path = "../../wasmql-build" }
