[package]
name = "poem"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["codec"]

[dependencies]
codec = { path = "codec" }
wasmql = { path = "../.." }
poem = { version = "1", features = ["static-files"] }
tokio = { version = "1", features = ["rt-multi-thread"] }

[build-dependencies]
wasmql-build = { path = "../../wasmql-build" }
