[package]
name = "poem-react-ts"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["codec"]

[[bin]]
name = "server"
path = "server.rs"

[dependencies]
codec = { path = "codec" }
wasmql = { path = "../.." }
poem = { version = "1", features = ["static-files"] }
tokio = { version = "1", features = ["rt-multi-thread"] }

[build-dependencies]
wasmql-build = { path = "../../wasmql-build" }
